### PR TITLE
Resolve scss linting warnings

### PR DESCRIPTION
**Pull request by richmccartney**
## What's this PR do?

Starting point of resolving SCSS warning issues in MAAS GUI

## Where should the reviewer start?

Pull down the branch run ```npm i``` and then run ```gulp test```

## How should this be manually tested?

Running ```gulp test``` should show warnings and errors

View any changes in the demo within ```demo/index.html```

## Any background context you want to provide?

This is the start of a cleanup process for the MAAS GUI framework :)

### CODE REVIEW

**Comment by anthonydillon** [comment]
There are no QA instructions and running `gulp test` gives me the same amount of warnings as on `master`?

**Comment by richmccartney** [comment]
@anthonydillon my apologies, I've updated the PR. Noted that there are CI test failures so I'll look into that tomorrow

**Comment by richmccartney** [comment]
@anthonydillon / @Lukewh / @grahambancroft can anyone take another quick look at this please.

**Comment by MariaVrachni** [comment]
@anthonydillon Is this repo still alive?

**Comment by anthonydillon** [comment]
It's not actively developed but is used by the MAAS team.

**Pull request closed without merging**
